### ISSUE TITLE
Newline character in string makes a new row

### ISSUE THREAD

**Issue by manotone** [sinbad/UnityCsvUtil#5]
Hi there! I was wondering if the issue with strings that span more that one line is already known? It causes the string to be split across two rows like in the screenshot I've attached.

Thanks!

![Annotation 2019-08-15 135024](https://user-images.githubusercontent.com/20519454/63095654-ac022500-bf63-11e9-86cb-232fcfb5c2e3.jpg)

**Comment by sinbad** [comment]
It's not been reported before, but you could perhaps resolve this by changing:

```
static char[] quotedChars = new char[] { ',', ';'};
```

to 

```
static char[] quotedChars = new char[] { ',', ';', '\n'};
```

LMK if that works for you / submit a PR if you like 👍

**Comment by manotone** [comment]
That worked! Thanks very much. I looked at the Pull Request section but haven't done it before and couldn't figure out how to do it, it wouldn't let me create one without there being multiple branches.

**Comment by sinbad** [comment]
No worries, I'll just fix it here. Glad that worked!
