### ISSUE TITLE
Can UnityCsvUtil export/import while not playing?

### ISSUE THREAD

**Issue by kaninhot004** [sinbad/UnityCsvUtil#6]
```
   [Button]
    public void ExportGameDataCSV()
    {
        DebugController.Log("ExportGameDataCSV");
        Sinbad.CsvUtil.SaveObject(GameDataController.Instance.GameData.data, "GameData.csv");
    }
```
I try to run at runtime it's exported.
But when I'm trying to use it when not playing it's seem doesn't working.

Thank you!

**Comment by sinbad** [comment]
You'll need to debug this to determine why, I suspect it's not actually the CsvUtil that's the issue, more likely that maybe your game data is not initialised in the editor.

**Comment by kaninhot004** [comment]
Thank you I will checking on it!
