### ISSUE TITLE
Is there any way to optimize the efficiency of SetField?

### ISSUE THREAD

**Issue by zyowo** [sinbad/UnityCsvUtil#8]
When I deserialized a `List` of less than 30 elements, it consumed nearly `100 ms` of CPU time. I checked Profiler and found that a lot of time was spent comparing Fields. Is there any way to ensure the order of the fields to reduce the check?

![QQ截图20200916095626](https://user-images.githubusercontent.com/30146416/93283642-851bbf80-f803-11ea-8b37-9d2557868c6b.png)

**Comment by sinbad** [comment]
This library was mostly intended for load time use, and mainly just during development so it’s easier to experiment with changes while doing payer tests without rebuilding every time. For that reason it’s not optimised for speed but more for ease of use. If you wanted to change how the data is matched to optimise it, using positional matching instead, you could do that by adding some metadata to the types, but it would be less easy to use. I'm not working on this library any more (I don’t use Unity any more) but feel free to submit a PR if you find a way to make it faster.

**Comment by zyowo** [comment]
Thank you for your reply. I tried to deserialize the elements in order, which can save half of the time, but as you said, there is a certain loss of stability and ease of use, so I don’t plan to submit it. Finally, thank you for providing this Great tool!
